# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Evan Wells, Ph.D.
title: Chemical Engineering Ph.D. looking for opportunities in biopharma
email: wellsevana@gmail.com
website: evanwells.net

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: WellsEvan
linkedin_username: evan-wells-phd-79981171
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: evanwells.net
  icon: fas fa-globe
  url: https://evanwells.net
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
 My name is Evan Wells and I am a PhD chemical engineer with expertise in mammalian cell culture, protein production, and protein characterization.

  I am most skilled in: <mark>antibody production</mark>, <mark>antibody glycosylation</mark> and <mark>maximizing cell culture efficiency</mark>.

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. 

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Carnegie Mellon University
        link: cmu.edu
        # link_text: cmu.edu
        sub_title: Graduate Researcher
        caption: August 2015 - December 2020
        quote: >
          Advisor: Prof. Anne Robinson,<br> Dissertation: Post-translational modifications to recombinant proteins: Roles in antibody production and neurodegenerative disease
        description: | # this will include new lines to allow paragraphs
            Determined the effects of media supplementation and process conditions on antibody production and antibody glycosylation in shake flask and bench-scale bioreactor CHO cell cultures.<br> Developed a platform for expressing and purifying phosphorylated tau from <i>E. coli</i> cultures. Characterized the effects of phosphorylation on tau protein isoelectric point and aggregation propensity. 

      - layout: left
        title: Brody School of Medicine
        link: ecu.edu
        # link_text: ecu.edu
        sub_title: Research Specialist
        caption: March 2014-June 2015
        quote: >
          Advisor: Prof. Tonya Zeczycki
        description: | # this will include new lines to allow paragraphs
            Expressed, purified, and kinetically characterized transglutaminase 2, a protein involved in neurodegenerative diseases. 

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Carnegie Mellon University
        caption: 2015-2020
        sub_title: Ph.D. Chemical Engineering
        quote: >
          Pittsburgh, PA
        description: | # this will include new lines to allow paragraphs
          In addition to my graduate work, I served in various department level and university wide leadership positions

      - layout: left
        title: East Carolina University
        caption: 2009-2013
        sub_title: B.S. Biochemistry, B.A. Chemistry
        quote: >
          Greenville, NC
        description: | # this will include new lines to allow paragraphs
          Outstanding senior award in Biochemistry

  - title: Publications # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Media supplementation for targeted manipulation of monoclonal antibody galactosylation and fucosylation
        link: https://onlinelibrary.wiley.com/doi/abs/10.1002/bit.27496
        quote: >
          Evan Wells, Liqing Song, Madison Greer, Yu Luo, Varghese Kurian, Babatunde Ogunnaike, Anne S Robinson
        description: | # this will include new lines to allow paragraphs
          We supplemented antibody-producing Chinese Hamster Ovary (CHO) cells with 2FP, galactose, and uridine and saw targeted effects on antibody glycosylation (e.g. galactosylation and fucosylation) without sacrificing culture growth or antibody yield. 
      - layout: top-middle
        title: Strategies to enhance productivity and modify product quality in therapeutic proteins
        link: https://www.sciencedirect.com/science/article/abs/pii/S2211339818300443
        quote: >
          Devesh Radhakrishnan, Evan A Wells, Anne Skaja Robinson
        description: | # this will include new lines to allow paragraphs
          A review focused on practical ways to improve protein production in CHO bioprocesses. 
      - layout: top-middle
        title: "Cellular engineering for therapeutic protein production: product quality, host modification, and process improvement"
        link: https://onlinelibrary.wiley.com/doi/abs/10.1002/biot.201600105
        quote: >
          Evan Wells, Anne Skaja Robinson
        description: | # this will include new lines to allow paragraphs
          A review highlighting different model organisms to produce recombinant proteins for therapeutic usage.
      - layout: top-middle
        title: 15 (V/K) kinetic isotope effect and steady-state kinetic analysis for the transglutaminase 2 catalyzed deamidation and transamidation reactions
        link: https://www.sciencedirect.com/science/article/abs/pii/S0003986118300547
        quote: >
          Evan A Wells, Mark A Anderson, Tonya N Zeczycki
        description: | # this will include new lines to allow paragraphs
          We determined the effects of increasing concentrations of putrescine on the kinetic mechanism of transglutaminase 2. 
                      
  - title: Personal Background
    layout: text
    content: | # this will include new lines to allow paragraphs
      I was born and raised in North Carolina. After undergrad, I moved to New Orleans to start graduate school at Tulane before following my advisor to Carnegie Mellon in Pittsburgh to finish my Ph.D. Aside from biotechnology, some of my other interests include:
      - Watching movies
      - Reading a mixture of science fiction, fantasy, and nonfiction books
      - Enjoying the outdoors
      - Cooking enjoyable meals



# Footer
footer_show_references: true
# references_title: References on request. (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
